apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web-deployment
  labels:
    type: backend
    app: java-web
spec: 
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: java-web
  template:
    metadata:
      name: java-web-pod
      labels:
        type: backend
        app: java-web
    spec:
      containers:
        - name: java-web-container
          image: $CONTAINER
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m