apiVersion: v1
kind: Service
metadata:
  name: java-web-load-balancer-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    type: backend
    app: java-web
  