---
name: Build and Push Image to Google Cloud Platform
on:
  pull_request:
    branches: [ master ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: macro-parity-403112
      IMAGE_NAME: mysqlspringlab
      REGISTRY_LOCATION: europe-docker.pkg.dev
      VM_INSTANCE: java-webserver-instance
      VM_ZONE: us-central1-a	
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GH_ACTIONS_SERVICE_ACCOUNT_KEY }}

    - name: Build Docker Image
      run: |-
        python -c "import os; file = open('deployed-instance.json', 'w'); file.write(os.environ['DEPLOYED_INSTANCE_ACCOUNT_KEY']); file.close()"
        docker build -t ${{ env.IMAGE_NAME }}:latest . --build-arg SRC=mysqlspringlab --build-arg GCP_CREDENTIALS="deployed-instance.json" 
        rm deployed-instance.json
      env:
        DEPLOYED_INSTANCE_ACCOUNT_KEY : ${{secrets.DEPLOYED_INSTANCE_SERVICE_ACCOUNT_KEY}}

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker ${{ env.REGISTRY_LOCATION }} --quiet

    - name: Tag Docker image and push to Google Artifact Registry
      run: |-
        docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY_LOCATION }}/${{ env.PROJECT_ID }}/mysqlspringlab-registry/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY_LOCATION }}/${{ env.PROJECT_ID }}/mysqlspringlab-registry/${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.REGISTRY_LOCATION }}/${{ env.PROJECT_ID }}/mysqlspringlab-registry/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_LOCATION }}/${{ env.PROJECT_ID }}/mysqlspringlab-registry/${{ env.IMAGE_NAME }}:latest

    - name: Deploy to Compute VM
      run: |-
        gcloud compute instances update-container ${{ env.VM_INSTANCE }} --zone ${{ env.VM_ZONE }} --container-image ${{ env.REGISTRY_LOCATION }}/${{ env.PROJECT_ID }}/mysqlspringlab-registry/${{ env.IMAGE_NAME }}:${{ github.sha }}
        